name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - TheCommieAxolotl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened and what you expected to happen!
      placeholder: ...Happened
      value: ""
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Velocity are you using?
      value: ""
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributor Guidelines](https://github.com/Velocity-Discord/Velocity/blob/main/.github/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Contributor Guidelines
          required: true
   - type: checkboxes
    id: unique
    attributes:
      label: Unique Issue
      description: You have checked that this issue is unique and has **not** been posted before
      options:
        - label: Yes, I have checked
          required: true
