name: Feature Request
description: Request a new feature
title: "[Feature] "
labels: ["request"]

assignees:
    - TheCommieAxolotl
body:
    - type: markdown
      attributes:
          value: "Thanks for suggesting a new feature!"
    - type: textarea
      id: describe
      attributes:
          label: Describe the feature
          description: Tell us what the feature is and why it's needed.
          placeholder: I would like to see...
          value: "I would like to see..."
      validations:
          required: true
    - type: input
      id: implementation
      attributes:
          label: Implementation
          description: Do you have an idea for how to implement this feature?
          placeholder: We could...
          value: "We could..."
      validations:
          required: false
    - type: textarea
      id: bug
      attributes:
          label: Does this feature relate to a bug?
          description: If so, please provide the bug's issue number/description.
          placeholder: ...
          value: "..."
      validations:
          required: false
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Contributor Guidelines](https://github.com/Velocity-Discord/Velocity/blob/main/.github/CONTRIBUTING.md)
          options:
              - label: I agree to follow this project's Contributor Guidelines
                required: true
    - type: checkboxes
      id: unique
      attributes:
          label: Unique Feature
          description: You have checked that this feature is unique and has **not** been posted before
          options:
              - label: Yes, I have checked
                required: true
