name: Bump Hash

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump Hash
        uses: TheCommieAxolotl/Bump-Hash-Action@v0.0.3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       - name: Commit files
      
#         run: |
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -m "Bump Hash" -a
#           git push -u origin main
