name: Release
on:
    push:
        branches:
            - "main"

jobs:
    dist:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 6.24.3
                  run_install: true

            - name: Build Files
              run: pnpm build

            - name: Package Asar
              run: pnpm bundle

            - name: Get Version
              if: "contains(github.event.head_commit.message, '[Release] ')"
              uses: sergeysova/jq-action@v2
              id: version
              with:
                  cmd: "jq -r .version package.json"

            - name: Get Hash
              if: "contains(github.event.head_commit.message, '[Release] ')"
              uses: sergeysova/jq-action@v2
              id: hash
              with:
                  cmd: "jq -r .hash package.json"

            - name: Release Stuff
              if: "contains(github.event.head_commit.message, '[Release] ')"
              run: |
                  gh release upload latest --clobber dist/velocity.asar
                  gh release edit latest --title $VERSION --notes "Release $VERSION ($HASH)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION: ${{ steps.version.outputs.result.value }}
                  HASH: ${{ steps.hash.outputs.result.value }}
